"""DTO 层：任务校验、protobuf 往返、代理 URL 构造。"""

import pytest

from ipclick.dto.models import (
    METHOD_MAP,
    DownloadResponse,
    DownloadTask,
    HttpMethod,
    IPClickAdapter,
    ProxyConfig,
)
from ipclick.dto.proto import task_pb2
from ipclick.dto.response import Response
from ipclick.exceptions import ValidationError


class TestDownloadTaskValidation:
    def test_url_required(self):
        with pytest.raises(ValidationError, match="URL is required"):
            DownloadTask(url="")

    @pytest.mark.parametrize("url", ["ftp://a.com", "file:///etc/passwd", "example.com"])
    def test_url_scheme_enforced(self, url: str):
        with pytest.raises(ValidationError, match="http"):
            DownloadTask(url=url)

    def test_multiple_body_types_rejected(self):
        with pytest.raises(ValidationError, match="multiple body types"):
            DownloadTask(url="http://a.com", data={"a": 1}, json={"b": 2})

    def test_negative_retries_rejected(self):
        with pytest.raises(ValidationError, match="max_retries"):
            DownloadTask(url="http://a.com", max_retries=-1)

    def test_non_positive_timeout_rejected(self):
        with pytest.raises(ValidationError, match="timeout"):
            DownloadTask(url="http://a.com", timeout=0)

    def test_curl_cffi_gets_default_impersonate(self):
        task = DownloadTask(url="http://a.com", adapter=IPClickAdapter.CURL_CFFI)
        assert task.impersonate == "chrome"


class TestToProtobuf:
    def test_explicit_presence_is_set_for_tri_state_fields(self):
        """回归：verify_ssl 必须显式落到线上。

        proto3 隐式默认值曾让"未设置"和"设为 false"无法区分，服务端因而
        对每个请求都关闭了证书校验。
        """
        pb = DownloadTask(url="http://a.com", verify=True).to_protobuf()
        assert pb.HasField("verify_ssl")
        assert pb.verify_ssl is True

    def test_verify_false_round_trips(self):
        pb = DownloadTask(url="http://a.com", verify=False).to_protobuf()
        assert pb.HasField("verify_ssl")
        assert pb.verify_ssl is False

    def test_explicit_zero_retries_distinguishable_from_unset(self):
        pb = DownloadTask(url="http://a.com", max_retries=0).to_protobuf()
        assert pb.HasField("max_retries")
        assert pb.max_retries == 0

        unset = task_pb2.ReqTask(url="http://a.com")
        assert not unset.HasField("max_retries")

    def test_uuid_autogenerated_when_blank(self):
        pb = DownloadTask(url="http://a.com").to_protobuf()
        assert pb.uuid

    def test_non_string_header_values_are_serialized(self):
        pb = DownloadTask(url="http://a.com", headers={"X-Num": 42}).to_protobuf()
        assert pb.headers["X-Num"] == "42"

    def test_cookie_string_is_parsed_into_map(self):
        pb = DownloadTask(url="http://a.com", cookies="a=1; b=2").to_protobuf()
        assert dict(pb.cookies) == {"a": "1", "b": "2"}

    def test_cookie_dict_passes_through(self):
        pb = DownloadTask(url="http://a.com", cookies={"session": "abc"}).to_protobuf()
        assert dict(pb.cookies) == {"session": "abc"}

    def test_proxy_config_object_is_converted(self):
        proxy = ProxyConfig(scheme="http", host="1.2.3.4", port=8080)
        pb = DownloadTask(url="http://a.com", proxy=proxy).to_protobuf()
        assert pb.proxy == "http://1.2.3.4:8080"

    def test_proxy_true_rejected_at_dto_layer(self):
        """proxy=True 只有 SDK 能解析，直接构造 DownloadTask 时必须报错而非静默忽略。"""
        with pytest.raises(ValidationError, match="proxy=True"):
            DownloadTask(url="http://a.com", proxy=True).to_protobuf()

    def test_adapter_accepts_string_name(self):
        pb = DownloadTask(url="http://a.com", adapter="httpx").to_protobuf()
        assert pb.adapter == IPClickAdapter.HTTPX.pb_value

    def test_falsy_body_values_still_transmitted(self):
        """data=0 / json={} 是有意义的请求体，不能因为 falsy 就被丢掉。"""
        assert DownloadTask(url="http://a.com", data=0).to_protobuf().data == "0"
        assert DownloadTask(url="http://a.com", json={}).to_protobuf().json == "{}"


class TestAdapterEnum:
    def test_from_str_is_case_insensitive(self):
        assert IPClickAdapter.from_str("HTTPX") is IPClickAdapter.HTTPX

    def test_unknown_name_raises_instead_of_silent_fallback(self):
        """回归：拼错适配器名以前会静默退回 curl_cffi。"""
        with pytest.raises(ValueError, match="未知的适配器名称"):
            IPClickAdapter.from_str("htpx")

    def test_unknown_pb_value_raises(self):
        with pytest.raises(ValueError, match="未知的适配器枚举值"):
            IPClickAdapter.from_pb(999)

    def test_method_map_matches_enum(self):
        assert METHOD_MAP[HttpMethod.GET.value] == "GET"
        assert METHOD_MAP[HttpMethod.DELETE.value] == "DELETE"
        assert len(METHOD_MAP) == len(HttpMethod)


class TestProxyConfig:
    def test_returns_none_without_host_or_tunnel(self):
        assert ProxyConfig().to_url() is None

    def test_basic_url(self):
        assert ProxyConfig(host="127.0.0.1", port=7890).to_url() == "http://127.0.0.1:7890"

    def test_auth_included(self):
        url = ProxyConfig(host="h", port=1, auth_key="u", auth_password="p").to_url()
        assert url == "http://u:p@h:1"

    def test_tunnel_server_overrides_host_port(self):
        url = ProxyConfig(host="ignored", port=1, tunnel_server="gw.example.com:9000").to_url()
        assert url == "http://gw.example.com:9000"

    def test_tunnel_only_still_produces_url(self):
        assert ProxyConfig(tunnel_server="gw:1").to_url() == "http://gw:1"


class TestDownloadResponse:
    def test_from_protobuf_exposes_adapter_name_not_int(self):
        """回归：adapter_type 以前直接塞 protobuf 枚举整数。"""
        pb = task_pb2.TaskResp(
            request_uuid="u1",
            adapter=IPClickAdapter.HTTPX.pb_value,
            status_code=200,
            content=b'{"ok": true}',
        )
        resp = DownloadResponse.from_protobuf(pb)
        assert resp.adapter_type == "httpx"
        assert resp.json() == {"ok": True}

    def test_from_response_does_not_crash(self):
        """回归：以前漏传两个必填字段，任何调用都必崩。"""
        resp = DownloadResponse.from_response(
            Response(url="http://a.com", status_code=200, content=b"hi"),
            request_uuid="u1",
            adapter_type="httpx",
        )
        assert resp.status_code == 200
        assert resp.text == "hi"
        assert resp.adapter_type == "httpx"

    def test_from_response_rejects_wrong_type(self):
        with pytest.raises(TypeError):
            DownloadResponse.from_response({"not": "a response"})

    def test_from_error_marks_failure(self):
        resp = DownloadResponse.from_error("boom", url="http://a.com")
        assert resp.status_code == -1
        assert resp.error == "boom"
        assert not resp.is_success()

    def test_is_success_and_ok_agree(self):
        resp = DownloadResponse(status_code=204)
        assert resp.is_success() is True
        assert resp.ok is True

    def test_error_makes_response_unsuccessful_despite_2xx(self):
        resp = DownloadResponse(status_code=200, error="upstream blew up")
        assert not resp.is_success()

    def test_invalid_json_raises_value_error(self):
        with pytest.raises(ValueError, match="not valid JSON"):
            DownloadResponse(status_code=200, text="<html>").json()

    def test_raise_for_status_raises_documented_subclass(self):
        """回归：抛的是基类 IPClickError，而 README 文档写的是 RequestError。
        RequestError 是 IPClickError 的子类，所以按文档写 `except RequestError:`
        的用户代码根本捕获不到。"""
        from ipclick.exceptions import RequestError

        with pytest.raises(RequestError):
            DownloadResponse(status_code=500, error="boom").raise_for_status()

    def test_raise_for_status_silent_on_success(self):
        DownloadResponse(status_code=200).raise_for_status()
