# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import task_pb2 as task__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in task_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub:
    """=====================================
    服务定义
    =====================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/task.TaskService/Send',
                request_serializer=task__pb2.ReqTask.SerializeToString,
                response_deserializer=task__pb2.TaskResp.FromString,
                _registered_method=True)
        self.SendStream = channel.unary_stream(
                '/task.TaskService/SendStream',
                request_serializer=task__pb2.ReqTask.SerializeToString,
                response_deserializer=task__pb2.TaskRespChunk.FromString,
                _registered_method=True)
        self.SendBatch = channel.stream_stream(
                '/task.TaskService/SendBatch',
                request_serializer=task__pb2.ReqTask.SerializeToString,
                response_deserializer=task__pb2.TaskResp.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/task.TaskService/Ping',
                request_serializer=task__pb2.PingReq.SerializeToString,
                response_deserializer=task__pb2.PingResp.FromString,
                _registered_method=True)
        self.Component = channel.unary_unary(
                '/task.TaskService/Component',
                request_serializer=task__pb2.ComponentReq.SerializeToString,
                response_deserializer=task__pb2.ComponentResp.FromString,
                _registered_method=True)


class TaskServiceServicer:
    """=====================================
    服务定义
    =====================================

    """

    def Send(self, request, context):
        """单次请求，响应体整条返回。适合中小响应。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStream(self, request, context):
        """流式下载：响应体分片返回，服务端与客户端都不需要把整个 body 驻留内存。
        大文件请用这个而不是 Send。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBatch(self, request_iterator, context):
        """批量：客户端流式推送任务，服务端按**完成顺序**（不是提交顺序）流式返回结果。
        相比逐个调用 Send，省掉了每个任务一次往返的开销。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """节点探测：验连通性与集群内部鉴权，不做任何业务动作。
        0.4 新增——对着 0.3 的节点调会收到 UNIMPLEMENTED，调用方据此判断"连上了、
        鉴权也过了，只是那台还没升级"。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Component(self, request, context):
        """远程管理可选组件。0.5 新增，**默认关闭**（见 ComponentReq 的说明）。
        对着 0.4 及更早的节点调会收到 UNIMPLEMENTED，主控据此提示"那台还没升级"。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=task__pb2.ReqTask.FromString,
                    response_serializer=task__pb2.TaskResp.SerializeToString,
            ),
            'SendStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SendStream,
                    request_deserializer=task__pb2.ReqTask.FromString,
                    response_serializer=task__pb2.TaskRespChunk.SerializeToString,
            ),
            'SendBatch': grpc.stream_stream_rpc_method_handler(
                    servicer.SendBatch,
                    request_deserializer=task__pb2.ReqTask.FromString,
                    response_serializer=task__pb2.TaskResp.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=task__pb2.PingReq.FromString,
                    response_serializer=task__pb2.PingResp.SerializeToString,
            ),
            'Component': grpc.unary_unary_rpc_method_handler(
                    servicer.Component,
                    request_deserializer=task__pb2.ComponentReq.FromString,
                    response_serializer=task__pb2.ComponentResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'task.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('task.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService:
    """=====================================
    服务定义
    =====================================

    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task.TaskService/Send',
            task__pb2.ReqTask.SerializeToString,
            task__pb2.TaskResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/task.TaskService/SendStream',
            task__pb2.ReqTask.SerializeToString,
            task__pb2.TaskRespChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/task.TaskService/SendBatch',
            task__pb2.ReqTask.SerializeToString,
            task__pb2.TaskResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task.TaskService/Ping',
            task__pb2.PingReq.SerializeToString,
            task__pb2.PingResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Component(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task.TaskService/Component',
            task__pb2.ComponentReq.SerializeToString,
            task__pb2.ComponentResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
