BASE_URL = "https://httpbun.com"
HTTPBIN_GET_URL = f"{BASE_URL}/get"
HTTPBIN_POST_URL = f"{BASE_URL}/post"
HTTPBIN_HEADERS_URL = f"{BASE_URL}/headers"
HTTPBIN_UA_URL = f"{BASE_URL}/user-agent"
HTTPBIN_IP_URL = f"{BASE_URL}/ip"
